GROUP_TITLE = 'Тестовая группа'
GROUP_SLUG = 'test_slug'
GROUP_DESCRIPTION = 'Тестовое описание'
GROUP_TITLE_2 = 'Вторая тестовая группа'
GROUP_SLUG_2 = 'test_slug_2'
GROUP_DESCRIPTION_2 = 'Другое тестовое описание'
POST_TEXT = 'Тестовый текст поста'
POST_AUTHOR = 'post_author'
